# try:
#     raise ValueError ("Errormessage")
# except ValueError as e:
#     print(e)

raise ValueError ("Errormessage")